server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.wang.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.wang: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

pattern:
  name: 本地环境local